### ISSUE TITLE
Detecting and erroring on unknown keys/attributes

### ISSUE THREAD

**Issue by dlenski** [Tinche/cattrs#113] opened 2021-01-13 19:43 UTC
* cattrs version: 1.0.0
* Python version: 3.6
* Operating System: Linux

### Description

As @ervteng wrote in [this comment on #35](https://github.com/Tinche/cattrs/issues/35#issuecomment-621607080), I would like to have a mechanism to raise an exception, or at least _detect_, the case where there are unknown/extra keys in a `dict` while `structure`ing from it.

### What I Did

```python
import attr
from cattr import structure

@attr.s
class Test:
    A: str = attr.ib()
    B: float = attr.ib()

# This succeeds, as intended:

print(structure(dict(A="foo", B=1.0), Test))

# This succeeds, but I want this to FAIL because it contains an extra/unknown attribute:

print(structure(dict(A="bar", B=3.14, C="huh? unknown!"), Test))
```

**Comment by dlenski** [comment] 2021-01-13 19:46
It appears that `structure` is doing some extra work to _avoid_ erroring on unknown attributes, since the underlying attr-classes _do_ raise exceptions if their constructors are given extra arguments:

```Test(A="bar", B=3.14, C="huh? unknown!")

**Comment by tmewett** [comment] 2021-01-19 17:15
I think this is a duplicate of #101 - Tinche has replied there also :+1:

**Comment by Tinche** [comment] 2021-01-19 18:10
Yep, this looks like a duplicate of #101

**Closed by Tinche** 2021-01-19 18:10 UTC
