### ISSUE TITLE
Default value is being ignored while structuring the attr class

### ISSUE THREAD

**Issue by shwetas1205** [Tinche/cattrs#14] opened 2017-10-27 14:08 UTC
* cattrs version: 0.5.0
* Python version: 3.6.2
* Operating System: Debian GNU/Linux 8.9 (jessie)

### Description

When I am trying use structure on an attr class having default values set for few optional attributes, those default values are being ignored and not returning to returned object

### What I Did
Here is the sample code:
```
import attr
from cattr import structure, typed
from typing import Optional


@attr.s
class A(object):
    a = typed(Optional[int], default=0)

@attr.s
class B(object):
    b = attr.ib(validator=optional(instance_of(int)), default=0)

```
When I tried ```structure({}, A)``` I expected ```A1(a=0)``` but I get ```A1(a=None)```
Similarly for ```structure({}, B)``` I get following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/cattr/converters.py", line 171, in structure
    return self.structure_func.dispatch(cl)(obj, cl)
  File "/xxx/cattr/converters.py", line 86, in <lambda>
    lambda *args, **kwargs: self.structure_attrs(*args, **kwargs))
  File "/xxx/cattr/converters.py", line 276, in structure_attrs_fromdict
    converted = self._structure_attr_from_dict(a, name, obj)
  File "/xxx/cattr/converters.py", line 286, in _structure_attr_from_dict
    return mapping[name]
KeyError: 'b'
```
A fix something like will fix the issue: https://github.com/shwetas1205/cattrs/commit/7d6d6fa102e662d0a59010e0184fbeebb9f4fa4d

**Comment by Tinche** [comment] 2017-10-27 21:23
Hi! This is a duplicate of #10 I think. It's something I will look at after attrs 17.3 is released and I do another development pass of cattrs. Thanks for your interest :)

**Closed by Tinche** 2017-10-27 21:23 UTC

**Comment by shwetas1205** [comment] 2017-10-31 12:32
Oops, I think I missed #10  Thanks for pointing that out. 

I wanted this support for one of my work so I went ahead added a fix here: https://github.com/Tinche/cattrs/pull/15 it would be great if you could have a look. Thanks :)
