### ISSUE TITLE
[requirement]Add feature to specific hidden fields?

### ISSUE THREAD

**Issue by Bryant-Yang** [Tinche/cattrs#99] opened 2020-10-15 08:56 UTC
I used marshmallow much before, and I'm trying to move to attrs with cattrs.

Is there any plan to add the feature to specify hidden/show fields when do un-structure?

I've write a helper class to do this:

```
from datetime import datetime
from decimal import Decimal
from typing import Optional, List

import cattr
import humps


class CAttrConverter:
    converter = cattr.Converter()
    dump_hidden_fields: Optional[List[str]] = None
    dump_specify_fields: Optional[List[str]] = None
    TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

    def __init__(self):
        """
        structure hook for load
        unstructure hook for dump
        """
        self.converter.register_structure_hook(Decimal, lambda val, _: Decimal(val) if val is not None else None)
        self.converter.register_unstructure_hook(Decimal, lambda val: float(val) if val is not None else None)

        self.converter.register_structure_hook(datetime,
                                               lambda val, _: datetime.strptime(val, self.TIME_FORMAT)
                                               if val is not None else None)
        self.converter.register_unstructure_hook(datetime,
                                                 lambda val: val.strftime(self.TIME_FORMAT)
                                                 if val is not None else None)


    def load(self, params, data_cls, camel_to_snake=True):
        """
        :param params: params, mostly from front end
        :param data_cls:
        :param camel_to_snake: need to convert from camel style to snake style
        """
        if camel_to_snake:
            params = humps.depascalize(params)
        return self.converter.structure(params, data_cls)

    def dump(self, data, snake_to_camel=False):
        """
        :param data:
        :param snake_to_camel: dump as camel case
        """
        result: dict = self.converter.unstructure(data)
        if self.dump_hidden_fields and isinstance(result, dict):
            for hidden_field in self.dump_hidden_fields:
                result.pop(hidden_field, None)

        if self.dump_specify_fields and isinstance(result, dict):
            hidden_fields = set(result.keys()) - set(self.dump_specify_fields)
            for hidden_field in hidden_fields:
                result.pop(hidden_field, None)

        if snake_to_camel:
            result = humps.camelize(result)

        return result
```

Suppose we have a attrs user data class, and want to dump as json without password_hash:
```
from attr import attrs

@attrs(auto_attribs=True)
class UserModel:
    user_name: str
    password_hash: str

class UserInfoConverter(CAttrConverter):
    dump_hidden_fields = ['password_hash']

result = UserInfoConverter().dump(UserModle('test_name', 'test_password'))

```

But this way only handle the first layer of the data instance(can't dump(List[UserModel])), I think it's better to have some hook params to specify which field to be hidden or shown, I make another implement as below, but seems not elegant enough, and the problem is that the cattrs converter actually replaced by attr.asdict(), for example, the datetime value format is not what I defined in CAttrConverter helper. 
```
from attr import asdict

class UserInfoConverter(CAttrConverter):
    dump_hidden_fields = ['password_hash']
    def __init__(self):
        super().__init__()
		self.converter.register_unstructure_hook(UserModel, lambda user: asdict(user, filter=lambda attr, val: attr.name not in self.dump_hidden_fields))
```

furthermore, the nested instance is not convtered by cattrs if use attr.asdict
```
@attrs
class Customer:
    full_name: str
    mobile: str
    account: UserModel

# 'account' should be dumped as the {'account': the user_name of UserModel instance}, but not {'account': UserModel as dict}
converter.register_unstructure_hook(UserModel, lambda account: account.user_name)
```

**Comment by Tinche** [comment] 2020-10-15 10:40
Hello,

I have something in the works I plan on releasing soon (https://cattrs.readthedocs.io/en/latest/customizing.html, https://github.com/Tinche/cattrs/blob/master/src/cattr/gen.py#L23) which allows you to apply overrides to specific fields, but it doesn't support unconditional removal of fields (just removal if they are equal to a default, or rename).

In your case, I would simply write an unstructure function by hand and register it for the `UserModel` class. The class is quite short and it's basically one line of code. Then, nested generics (like `list[UserModel]`) will work.

```
from attr import attrs
from cattr import Converter


@attrs(auto_attribs=True)
class UserModel:
    user_name: str
    password_hash: str


c = Converter()
c.register_unstructure_hook(UserModel, lambda u: {"user_name": u.user_name})

print(c.unstructure([UserModel("Username", "Password")]))

>>> [{'user_name': 'Username'}]
```

As for your second question, `attr.asdict` doesn't integrate with cattrs (this is by design, basically), so it can't call back into the converter. You can use `converter.unstructure_attrs_asdict` though, which does call back and is basically the same thing.

So, alternatively,

```
from attr import attrs
from cattr import Converter


@attrs(auto_attribs=True)
class UserModel:
    user_name: str
    password_hash: str


c = Converter()
c.register_unstructure_hook(
    UserModel,
    lambda u: {
        k: v
        for k, v in c.unstructure_attrs_asdict(u).items()
        if k != "password_hash"
    },
)

print(c.unstructure([UserModel("Username", "Password")]))
```

**Comment by Bryant-Yang** [comment] 2020-10-15 11:04
Thanks, I'll use unstructure_attrs_asdict do the nested stuff, and hidden fields will be filtered in dict comprehensions

**Comment by Tinche** [comment] 2020-10-15 21:10
Cool, ok if we close this?

**Closed** 2020-10-16 04:49 UTC
