### ISSUE TITLE
set of enums is not automatically unstructured

### ISSUE THREAD

**Issue by anthrotype** [Tinche/cattrs#48] opened 2018-10-29 13:28 UTC
* cattrs version: 0.9.0
* Python version: 3.7.1
* Operating System: Linux

### Description

I tried to call cattr.unstructure on a set containing enum.IntEnum values.
I expected that it would return a set of enum values (the wrapped `MyEnum(0).value`), whereas I got a set of enum objects, so effectively no unstructuring occurred.

Note that if I use a list of enums instead of a set, then the IntEnum values are unpacked and I get a list of integers.

### What I Did

```python
In [1]: import cattr

In [2]: from enum import IntEnum

In [3]: class MyEnum(IntEnum):
   ...:     A = 1
   ...:     B = 2
   ...:     C = 3
   ...:     

In [4]: lst = [MyEnum(1), MyEnum(2)]

In [5]: cattr.unstructure(lst)
Out[5]: [1, 2]

In [6]: s = {MyEnum(2), MyEnum(3)}

In [7]: cattr.unstructure(s)
Out[7]: {<MyEnum.B: 2>, <MyEnum.C: 3>}
```

In the last line, I would expect to get `{2, 3}` as the result.

**Comment by Tinche** [comment] 2018-10-29 17:54
Acknowledged, will look into this :)

**Comment by anthrotype** [comment] 2018-10-29 18:00
Thanks :+1:

**Comment by madsmtm** [comment] 2019-01-24 20:03
From what I can tell this is fixed in 0460fbe825a1e7e50919c5d80e412a309dd96c54

**Comment by ZhukovGreen** [comment] 2019-03-19 06:55
it looks like it is related to this:
```python
from typing import Tuple, Set
from datetime import datetime

import cattr
import attr
import pytest


TIME_FORMAT = "%Y-%m-%d %H:%M:%S"
COMPLEX_TYPE = Tuple[Tuple[str, datetime]]
COMPLEX_TYPE_BAD = Set[Tuple[str, datetime]]

cattr.register_unstructure_hook(
    datetime, lambda dt: datetime.strftime(dt, format=TIME_FORMAT)
)
cattr.register_structure_hook(
    datetime, lambda dt_str, _: datetime.strptime(dt_str, TIME_FORMAT)
)


def test_cattrs_io_for_a():
    @attr.s(auto_attribs=True)
    class A:
        ds: datetime = attr.ib(factory=datetime.utcnow)

    a = A()
    a_ser = cattr.unstructure(a)
    a_des = cattr.structure(a_ser, A)
    assert isinstance(a_des, A)


def test_cattrs_io_for_b():
    @attr.s(auto_attribs=True)
    class B:
        ds: COMPLEX_TYPE = attr.ib(factory=set)

    b = B((("a", datetime.utcnow()), ("b", datetime.utcnow())))
    b_ser = cattr.unstructure(b)
    b_des = cattr.structure(b_ser, B)
    assert isinstance(b_des, B)


def test_cattrs_io_for_b_bad():
    @attr.s(auto_attribs=True)
    class B:
        ds: COMPLEX_TYPE_BAD = attr.ib(factory=set)

    b = B({("a", datetime.utcnow()), ("b", datetime.utcnow())})
    b_ser = cattr.unstructure(b)
    with pytest.raises(TypeError):
        b_des = cattr.structure(b_ser, B)
        assert isinstance(b_des, B)
```
COMPLEX_TYPE_BAD isnot being unstructured

cattrs==0.9.0

**Comment by madsmtm** [comment] 2019-03-19 07:37
The fix hasn't yet been released. Please try running this from the current `master`

**Comment by ZhukovGreen** [comment] 2019-03-19 12:28
Thx

**Comment by bhargavrpatel** [comment] 2019-12-05 23:03
Hello -- Just following up on this. Is this fixed?

**Comment by ZhukovGreen** [comment] 2019-12-06 12:59
@bhargavrpatel the issue is still valid. Just tested it

**Comment by Tinche** [comment] 2021-03-21 22:24
This has been fixed for a long time I believe, so closing.

**Closed by Tinche** 2021-03-21 22:24 UTC
